# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pokemons_pb2 as pokemons__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pokemons_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PokemonsServiceStub(object):
    """Servicio de Pokémon
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePokemon = channel.unary_unary(
                '/pokemons.PokemonsService/CreatePokemon',
                request_serializer=pokemons__pb2.Pokemon.SerializeToString,
                response_deserializer=pokemons__pb2.Pokemon.FromString,
                _registered_method=True)
        self.ReadPokemon = channel.unary_unary(
                '/pokemons.PokemonsService/ReadPokemon',
                request_serializer=pokemons__pb2.PokemonRequest.SerializeToString,
                response_deserializer=pokemons__pb2.Pokemon.FromString,
                _registered_method=True)
        self.UpdatePokemon = channel.unary_unary(
                '/pokemons.PokemonsService/UpdatePokemon',
                request_serializer=pokemons__pb2.Pokemon.SerializeToString,
                response_deserializer=pokemons__pb2.Pokemon.FromString,
                _registered_method=True)
        self.DeletePokemon = channel.unary_unary(
                '/pokemons.PokemonsService/DeletePokemon',
                request_serializer=pokemons__pb2.PokemonRequest.SerializeToString,
                response_deserializer=pokemons__pb2.Empty.FromString,
                _registered_method=True)


class PokemonsServiceServicer(object):
    """Servicio de Pokémon
    """

    def CreatePokemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPokemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePokemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePokemon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokemonsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePokemon': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePokemon,
                    request_deserializer=pokemons__pb2.Pokemon.FromString,
                    response_serializer=pokemons__pb2.Pokemon.SerializeToString,
            ),
            'ReadPokemon': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPokemon,
                    request_deserializer=pokemons__pb2.PokemonRequest.FromString,
                    response_serializer=pokemons__pb2.Pokemon.SerializeToString,
            ),
            'UpdatePokemon': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePokemon,
                    request_deserializer=pokemons__pb2.Pokemon.FromString,
                    response_serializer=pokemons__pb2.Pokemon.SerializeToString,
            ),
            'DeletePokemon': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePokemon,
                    request_deserializer=pokemons__pb2.PokemonRequest.FromString,
                    response_serializer=pokemons__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pokemons.PokemonsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pokemons.PokemonsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PokemonsService(object):
    """Servicio de Pokémon
    """

    @staticmethod
    def CreatePokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemons.PokemonsService/CreatePokemon',
            pokemons__pb2.Pokemon.SerializeToString,
            pokemons__pb2.Pokemon.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadPokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemons.PokemonsService/ReadPokemon',
            pokemons__pb2.PokemonRequest.SerializeToString,
            pokemons__pb2.Pokemon.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemons.PokemonsService/UpdatePokemon',
            pokemons__pb2.Pokemon.SerializeToString,
            pokemons__pb2.Pokemon.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePokemon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pokemons.PokemonsService/DeletePokemon',
            pokemons__pb2.PokemonRequest.SerializeToString,
            pokemons__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
