# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pokemons.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'pokemons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epokemons.proto\x12\x08pokemons\"W\n\x07Pokemon\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0c\n\x04\x65\x64\x61\x64\x18\x04 \x01(\x05\x12\r\n\x05poder\x18\x05 \x01(\x02\"\x1c\n\x0ePokemonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xf7\x01\n\x0fPokemonsService\x12\x35\n\rCreatePokemon\x12\x11.pokemons.Pokemon\x1a\x11.pokemons.Pokemon\x12:\n\x0bReadPokemon\x12\x18.pokemons.PokemonRequest\x1a\x11.pokemons.Pokemon\x12\x35\n\rUpdatePokemon\x12\x11.pokemons.Pokemon\x1a\x11.pokemons.Pokemon\x12:\n\rDeletePokemon\x12\x18.pokemons.PokemonRequest\x1a\x0f.pokemons.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POKEMON']._serialized_start=28
  _globals['_POKEMON']._serialized_end=115
  _globals['_POKEMONREQUEST']._serialized_start=117
  _globals['_POKEMONREQUEST']._serialized_end=145
  _globals['_EMPTY']._serialized_start=147
  _globals['_EMPTY']._serialized_end=154
  _globals['_POKEMONSSERVICE']._serialized_start=157
  _globals['_POKEMONSSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
